version: "3.8"

services:
  db:
    image: postgres:15
    container_name: devpath-db
    restart: always
    environment:
      POSTGRES_DB: devpath
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5555:5432"
    volumes:
      - devpath-data:/var/lib/postgresql/data

volumes:
  devpath-data:
