spring.application.name=backend

# ===============================
# SERVER AYARLARI
# ===============================
server.port=8080

# ===============================
# VERİTABANI BAĞLANTISI
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/devpath
spring.datasource.username=postgres
# Şifrenin doğru olduğundan emin ol:
spring.datasource.password=SecurePass123!@#
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE AYARLARI
# ===============================
# Tabloları güncelle (Veri kaybetmeden yeni sütun ekler)
spring.jpa.hibernate.ddl-auto=update

# SQL sorgularını terminalde göster (Hata ayıklamak için)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# BAŞLANGIÇ AYARLARI (KRİTİK)
# ===============================
# ÖNCE tablolar güncellensin, SONRA data.sql çalışsın (Hata almamak için şart)
spring.jpa.defer-datasource-initialization=true

# data.sql dosyasını her zaman çalıştır
spring.sql.init.mode=always

# ===============================
# MAIL AYARLARI
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devpathai7@gmail.com
spring.mail.password=xalyysvxdbxvhhdh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true