spring.application.name=backend

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (PostgreSQL - Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5555/devpath
spring.datasource.username=admin
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# Tabloları her çalıştırmada oluştur (geliştirme ortamı için)
spring.jpa.hibernate.ddl-auto=create

# SQL'leri göster
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# !!! En önemli ayar !!!
# Hibernate tabloyu oluşturduktan sonra data.sql çalışsın
spring.jpa.defer-datasource-initialization=true

# Her zaman data.sql çalışsın
spring.sql.init.mode=always
